version: "2"
services:
  zookeeper:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/zookeeper:3.5.1
    expose:
      - "2181"
    environment:
      SEED_ZOOKEEPER: zookeeper

  kafka:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/kafka:0.10.0.1
    links:
      - zookeeper
    expose:
      - "9092"
      - "9999" #JMX
    environment:
      KAFKA_CREATE_TOPICS: "upstream.thermostat:1:1,hive.heating.period.sample:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper

  schema_registry:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/schema-registry:3.0
    links:
      - zookeeper
      - kafka
    expose:
      - "8081"
    environment:
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    command: >
      /bin/bash -c '
        while ! nc -w 1 -z kafka 9092;
         do sleep 1;
         echo "waiting for kafka...";
        done;
        schema-registry-docker.sh
      '

  kafka-connect:
    image: sqs-connector
    links:
      - kafka
      - schema_registry
    expose:
      - "8083"
    environment:
      KAFKA: kafka:9092
      SCHEMA_REGISTRY: http://schema_registry:8081