version: "2"
services:
  zookeeper:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/zookeeper:3.5.1
    expose:
      - "2181"
    environment:
      SEED_ZOOKEEPER: zookeeper

  kafka:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/kafka:0.9.0.0
    links:
      - zookeeper
    expose:
      - "9092"
      - "9999" #JMX
    environment:
      KAFKA_CREATE_TOPICS: "upstream.thermostat:1:1,hive.heating.period.sample:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper

  schema_registry:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/schema-registry:2.0
    links:
      - zookeeper
      - kafka
    expose:
      - "8081"
    environment:
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    command: >
      /bin/bash -c '
        while ! nc -w 1 -z kafka 9092;
         do sleep 1;
         echo "waiting for kafka...";
        done;
        schema-registry-docker.sh
      '

  job:
    image: bgchops-docker-dockerv2-local.artifactoryonline.com/bgch-dp/dp-heating-period-sample-job
    links:
      - kafka
      - schema_registry
    expose:
      - "7001"
      - "7002"
      - "7003"
      - "7004"
      - "7005"
      - "7006"
      - "8888" # Akka
    environment:
      SPARK_MASTER: spark://sparkmaster:7077
      KAFKA: kafka:9092
      SCHEMA_REGISTRY: http://schema_registry:8081
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: ""
      CASSANDRA_PASSWORD: ""
      RM_CHECKPOINT: /var/spark/checkpoints/tmp
      ENV: test
